"""
THE KRAKEN DREAMS - Export Formatters
Handles exporting transcripts to various formats.

Supports:
- Obsidian markdown (with wikilinks and frontmatter)
- Standard Markdown
- HTML with styling
- Plain text
"""

import os
import re
from datetime import datetime


def export_to_obsidian(transcript, title=None, speakers=None, session_date=None, campaign=None):
    """
    Export transcript to Obsidian-compatible markdown.
    
    Features:
    - YAML frontmatter for metadata
    - Wikilinks for speaker names (creates linked notes)
    - Proper heading structure
    - Tags for easy organization
    
    Args:
        transcript (str): The transcript text
        title (str): Session title
        speakers (list): List of speaker names
        session_date (str): Date of session
        campaign (str): Campaign name
        
    Returns:
        str: Obsidian-formatted markdown
    """
    # Default values
    title = title or "D&D Session"
    session_date = session_date or datetime.now().strftime("%Y-%m-%d")
    campaign = campaign or "Unknown Campaign"
    speakers = speakers or []
    
    # Build YAML frontmatter
    frontmatter = [
        "---",
        f"title: \"{title}\"",
        f"date: {session_date}",
        f"campaign: \"[[{campaign}]]\"",
        "type: session-transcript",
        "tags:",
        "  - dnd",
        "  - session",
        "  - transcript",
    ]
    
    if speakers:
        frontmatter.append("players:")
        for speaker in speakers:
            frontmatter.append(f"  - \"[[{speaker}]]\"")
    
    frontmatter.append("---")
    frontmatter.append("")
    
    # Build content
    content = [
        f"# {title}",
        "",
        f"**Campaign:** [[{campaign}]]",
        f"**Date:** {session_date}",
        "",
    ]
    
    # Party members section with wikilinks
    if speakers:
        content.append("## Party Members")
        content.append("")
        for speaker in speakers:
            content.append(f"- [[{speaker}]]")
        content.append("")
    
    # Transcript section
    content.append("## Session Transcript")
    content.append("")
    
    # Convert transcript with wikilinks for speakers
    for line in transcript.split('\n'):
        # Match [timestamp] Speaker: text format
        match = re.match(r'\[(\d+:\d+(?::\d+)?)\]\s+([^:]+):\s*(.*)', line)
        if match:
            timestamp, speaker, text = match.groups()
            # Create wikilink for speaker
            content.append(f"**[{timestamp}]** [[{speaker}]]: {text}")
        elif line.strip():
            content.append(line)
        else:
            content.append("")
    
    # Combine frontmatter and content
    return '\n'.join(frontmatter) + '\n'.join(content)


def export_to_markdown(transcript, title=None, speakers=None):
    """
    Export transcript as standard markdown.
    
    Args:
        transcript (str): The transcript text
        title (str): Session title
        speakers (list): List of speaker names
        
    Returns:
        str: Markdown-formatted transcript
    """
    title = title or "D&D Session Transcript"
    
    lines = [
        f"# {title}",
        "",
        f"*Generated by The Kraken Dreams*",
        "",
        "---",
        ""
    ]
    
    if speakers:
        lines.append("## Participants")
        lines.append("")
        for speaker in speakers:
            lines.append(f"- {speaker}")
        lines.append("")
        lines.append("---")
        lines.append("")
    
    lines.append("## Transcript")
    lines.append("")
    
    current_speaker = None
    for line in transcript.split('\n'):
        match = re.match(r'\[(\d+:\d+(?::\d+)?)\]\s+([^:]+):\s*(.*)', line)
        if match:
            timestamp, speaker, text = match.groups()
            if speaker != current_speaker:
                lines.append(f"\n### {speaker}\n")
                current_speaker = speaker
            lines.append(f"**[{timestamp}]** {text}")
        elif line.strip():
            lines.append(line)
    
    return '\n'.join(lines)


def export_to_html(transcript, title=None, speaker_colors=None):
    """
    Export transcript as styled HTML.
    
    Args:
        transcript (str): The transcript text
        title (str): Session title  
        speaker_colors (dict): Speaker name -> hex color
        
    Returns:
        str: HTML-formatted transcript
    """
    title = title or "D&D Session Transcript"
    speaker_colors = speaker_colors or {}
    
    html = [
        "<!DOCTYPE html>",
        "<html><head>",
        "<meta charset='utf-8'>",
        f"<title>{title}</title>",
        "<style>",
        "body { background: #0a0a0f; color: #e0e0e8; font-family: 'Segoe UI', sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; }",
        "h1 { color: #9d8dc7; border-bottom: 2px solid #9d8dc7; padding-bottom: 10px; }",
        "h2 { color: #7bc7c7; }",
        ".timestamp { color: #8888a0; font-size: 0.9em; }",
        ".line { margin: 8px 0; padding: 5px 10px; border-left: 3px solid #333; }",
        ".speaker { font-weight: bold; }",
        "footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #333; color: #666; font-size: 0.8em; }",
        "</style>",
        "</head><body>",
        f"<h1>🐙 {title}</h1>",
        "<p><em>Generated by The Kraken Dreams</em></p>",
        "<hr>",
    ]
    
    for line in transcript.split('\n'):
        match = re.match(r'\[(\d+:\d+(?::\d+)?)\]\s+([^:]+):\s*(.*)', line)
        if match:
            timestamp, speaker, text = match.groups()
            color = speaker_colors.get(speaker, "#e0e0e8")
            html.append(
                f"<div class='line' style='border-left-color:{color};'>"
                f"<span class='timestamp'>[{timestamp}]</span> "
                f"<span class='speaker' style='color:{color};'>{speaker}:</span> {text}</div>"
            )
        elif line.strip():
            html.append(f"<div class='line'>{line}</div>")
    
    html.extend([
        "<footer>Generated by The Kraken Dreams - D&D Session Tools</footer>",
        "</body></html>"
    ])
    
    return '\n'.join(html)


def get_export_formats():
    """
    Get list of supported export formats.
    
    Returns:
        list: List of (format_id, display_name, extension) tuples
    """
    return [
        ("txt", "Plain Text", ".txt"),
        ("md", "Markdown", ".md"),
        ("obsidian", "Obsidian Markdown", ".md"),
        ("html", "HTML (Styled)", ".html"),
    ]
